export const VALID_LICITATION_FIELDS = [
	"Expediente",
	"ID de publicación en TED",
	"Órgano de Contratación",
	"ID del Órgano de Contratación",
	"Estado de la Licitación",
	"Objeto del contrato",
	"Financiación UE",
	"Presupuesto base de licitación sin impuestos",
	"Valor estimado del contrato:",
	"Tipo de Contrato:",
	"Código CPV",
	"Lugar de Ejecución",
	"Sistema de contratación",
	"Procedimiento de contratación",
	"Tipo de tramitación",
	"Información",
	"Método de presentación de la oferta",
	"Fecha fin de presentación de oferta",
	"Fecha de Actualización del Expte.",
	"Destinatario del contrato",
	"Resultado",
	"Adjudicatario",
	"Nº de Licitadores Presentados",
	"Importe de Adjudicación",
]

export const DEFAULT_LIMIT = 10
